---
--- Generated by Luanalysis
--- Created by fk.
--- DateTime: 08.09.22 07:07
---
local awful = require("awful")

function spawn_once(command, class)
    -- create move callback
    local callback
    callback = function(c)
        if c.class == class then
            awful.client.movetotag(tag, c)
            client.remove_signal("manage", callback)
        end
    end
    client.add_signal("manage", callback)
    -- now check if not already running!
    local findme = command
    local firstspace = findme:find(" ")
    if firstspace then
        findme = findme:sub(0, firstspace-1)
    end
    -- finally run it
    awful.util.spawn_with_shell("pgrep -u $USER -x " .. findme .. " > /dev/null || (" .. command .. ")")
end

-- use the spawn_once
spawn_once("teams", "Teams")
spawn_once("jetbrains-toolbox", "Toolbox")
spawn_once("keepassxc", "KeePassXC")
spawn_once("nm-applet", "nm-applet")


awful.util.spawn_with_shell("autorandr docked")